name: login_flutter_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.2
  google_fonts: ^6.1.0

  ## -- STATE MANAGEMENT
  get: ^4.6.6
  get_storage: ^2.1.1

  ## -- OnBoarding PACKAGES
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.1.0

  ## -- OTP TEXT FIELD PACKAGE
  flutter_otp_text_field: ^1.1.1

  ## -- FIREBASE PACKAGES
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  flutter_facebook_auth: ^7.1.1
  google_sign_in: ^6.2.2


  ## -- ICON PACKAGES
  cupertino_icons: ^1.0.6
  line_awesome_flutter: ^2.0.0
  flutter_native_splash: ^2.4.3


  ## -- FILE PICKER
  file_picker: ^5.2.1


  ## -- Memory
  flutter_cache_manager: ^3.0.0

  ## -- Guard Assistant
  intl: ^0.19.0
  google_generative_ai: ^0.2.0
  flutter_spinkit: ^5.2.0
  animated_text_kit: ^4.2.2
  flutter_markdown: ^0.6.20
  win32: ^5.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
    - assets/images/profile/
    - assets/images/dashboard/
    - assets/images/splash_images/
    - assets/images/welcome_images/
    - assets/images/forget_password/
    - assets/images/on_boarding_images/

# Splash screen has been added in the 'splash.yaml' file in main project directory